export const environment = {
  production: false,

  UrlBase: 'https://cilantroapp.herokuapp.com',
  Login: '/login',
  crearUsuario: '/usuario/crear',
  crearHistoria: '/historia/crear',
  allhistorias: '/historia/obtenerTodas',
  allUsuarios: '/usuario/listarPorRol/',
  allHistorias: '/historia/obtenerTodas',
  allHistoriasLider: '/historia/obtenerPorLiderTecnicoId/',
  allHistoriasDev: '/historia/obtenerPorDesarrolladorId/',
  eliminarHistoria: '/historia/eliminar/',
  ListarPorRol: '/usuario/listarPorRol/',
  crearTarea: '/tarea/crear',
  ListarPorId: '/usuario/',
  CrearProyecto: '/proyecto/crear',
  editarTarea: '/tarea/editar',
  actualizarHistoria: '/historia/actualizar',
  AsignarProyecto: '/proyecto/asignar',
  ListarProyectoPorId: '/proyecto/',
  EliminarProyecto: '/eliminarProyecto/',
  listarproyectos: '/listarProyectos',
  eliminarTarea: '/eliminarTarea/',
  ListarHistoriasPorIdProyecto: '/historia/obtenerPorProyecto/',
  listarTareaPorId: '/tarea/listarPorId/',
};
